### ISSUE TITLE
A unwrap function for arrays in ObjectPools.jl

### ISSUE THREAD

**Issue by CheukHinHoJerry** [ACEsuit/ObjectPools.jl#11]
A reminder for us to take care of the possibly unwanted behavior in using `parent(A)` to unwrap `FlexArray` or `FlexArrayCache` into `PtrArray`.

**Comment by cortner** [comment]
this is really quick. Would you like to do it yourself? Otherwise it will take me 15 minutes to implement, test and register.

**Comment by CheukHinHoJerry** [comment]
Yes sure. I will do this possibly tmr. Busy with cleaning up the `ACESchrodinger.jl` today (so that Bernie can read those in details easier and we can release that later...).

**Comment by cortner** [comment]
to be closed by #12
